### ISSUE TITLE
Timeout problem

### ISSUE THREAD

**Issue by Elisa4591** [drementer/lazy-load.js#1]
Hello, I need some advice.
We are trying to solve the problems concerning the timeout which appears to be very long and the site consequently also slowed down.
Could it be because we have lazy loading enabled? In your opinion, is it optimal to have both lazy load and infinity scroll active on a HB structure? Thanks

**Comment by drementer** [comment]
Hello, first of all, thank you for your feedback.

I never tested it with infinite scroll, but I guess the more images you want to lazy load will cause your system to use more ram. Of course, this causes performance losses.

Thinking that the root of the problem may stem from this project, there is another method I can suggest. You can use ['lazy' attr](https://www.youtube.com/watch?v=gtxO_niDC5M) for images and iframes.
But the browser support of this [method](https://caniuse.com/?search=lazy) is not as much as this [project](https://caniuse.com/?search=IntersectionObserver)

Finally, if you write a few images and a more detailed article, I can help you better.
